In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

%matplotlib inline

In [2]:
train = pd.read_csv("train.csv")
leaderboard = pd.read_csv("leaderboard_dataset.csv")
test = pd.read_csv("test.csv")

In [3]:
train[train["VAR21"]=="High"]

,VAR1,VAR2,VAR3,VAR4,VAR5,VAR6,VAR7,VAR8,VAR9,VAR10,...,VAR12,VAR13,VAR14,VAR15,VAR16,VAR17,VAR18,VAR19,VAR20,VAR21
1,2,911.764706,0.027778,NaN,611.574748,8.181818,1.344479,198.600020,22.086661,NaN,...,15.012510,NaN,1,NaN,1.614613,NaN,0,1,146.654045,High
4,5,914.117647,0.083333,NaN,626.514988,5.181818,1.372928,198.790477,85.938202,58.632548,...,210.175146,NaN,.,NaN,1.558341,NaN,1,0,101.268503,High
13,14,882.352941,0.833333,178.571429,611.574748,6.636364,0.655025,197.075291,22.086661,NaN,...,NaN,NaN,1,NaN,0.984960,NaN,0,1,342.450947,High
15,16,808.235294,8.333333,678.571429,611.574748,NaN,0.585166,196.987351,22.206442,NaN,...,300.250208,4.000000,1,4.000000,0.966037,1000.00,0,1,57.633391,High
30,31,845.882353,1.944444,107.142857,690.263984,11.363636,1.166687,197.809000,3.306796,53.158788,...,NaN,NaN,2,NaN,1.552790,NaN,0,1,133.807229,High
33,34,883.529412,0.138889,642.857143,733.297270,4.545455,3.816744,212.605150,NaN,48.981559,...,210.175146,16.613333,2,16.613333,2.779121,1000.00,0,1,138.414802,High
34,35,940.000000,0.138889,35.714286,620.455910,39.090909,0.616254,197.023002,10.887188,58.632548,...,NaN,20.000000,2,20.000000,0.970746,NaN,0,1,103.497418,High
36,37,887.058823,0.111111,285.714286,662.438792,4.545455,0.769814,197.408885,NaN,58.632548,...,NaN,NaN,1,NaN,1.145384,NaN,1,0,120.220310,High
44,45,880.000000,0.111111,678.571429,679.870240,22.727273,6.011623,203.296665,NaN,58.632548,...,250.208507,9.066667,3,9.066667,4.754492,617.21,1,0,386.598967,High
57,58,994.117647,1.216667,35.714286,629.475376,9.090909,1.284523,198.479924,243.907239,58.632548,...,200.166806,12.666667,1,12.666667,1.491383,NaN,1,0,96.041308,High
62,63,956.470588,0.166667,214.285714,625.882995,10.909091,1.048611,198.291067,32.832680,58.632548,...,150.125104,NaN,1,NaN,1.274181,NaN,0,0,91.509466,High
78,79,902.352941,0.083333,71.428571,624.058795,9.090909,1.667400,197.544615,51.539821,58.632548,...,40.033361,11.333333,2,11.333333,1.786133,NaN,0,1,106.220310,High
81,82,807.058824,1.111111,928.571429,611.574748,9.090909,0.632387,197.014964,18.108239,NaN,...,50.041701,7.600000,1,7.600000,1.015677,978.74,0,1,0.000000,High
85,86,968.235294,2.094267,NaN,611.706048,22.727273,0.598263,197.055261,7.101270,48.139029,...,110.925772,26.666667,1,26.666667,0.988174,NaN,1,1,101.345955,High
115,116,777.647059,1.382478,500.000000,672.286326,13.636364,1.663644,198.184006,NaN,58.632548,...,100.083403,4.333333,1,4.333333,1.617287,NaN,0,0,64.179002,High
117,118,851.764706,4.166667,250.000000,613.521496,22.727364,0.636425,197.213356,NaN,58.632548,...,210.175146,13.333333,2,13.333333,1.010590,NaN,0,0,78.986231,High
123,124,875.294118,0.166667,107.142857,637.953884,13.636364,0.999317,199.123234,0.342230,58.632548,...,NaN,10.800000,1,10.800000,1.183347,1000.00,1,0,159.191050,High
124,125,964.705882,1.666667,35.714286,622.940115,8.181818,1.104439,198.007216,NaN,58.632548,...,210.175146,13.333333,2,13.333333,1.321526,1000.00,1,0,171.650602,High
126,127,1000.000000,11.111111,35.714286,711.517150,36.363636,8.066293,213.043602,NaN,58.632548,...,930.775646,4.000000,1,4.000000,6.209168,NaN,0,0,642.490534,High
135,136,945.882353,0.138889,NaN,618.211548,NaN,2.674951,197.556836,NaN,58.632548,...,138.448707,3.553333,2,3.553333,2.605861,NaN,1,0,373.089501,High
138,139,888.235294,0.111111,71.428571,658.251183,6.818182,0.820533,200.133138,NaN,56.374354,...,NaN,3.333333,2,3.333333,1.105877,1000.00,1,1,129.566265,High
146,147,923.529412,NaN,NaN,612.478095,NaN,1.799911,197.160119,NaN,58.509120,...,48.373645,NaN,3,NaN,1.672975,NaN,0,1,107.022375,High
147,148,903.529412,1.976667,178.571429,611.574748,6.363636,0.559710,196.911295,22.086661,47.899686,...,NaN,10.000000,1,10.000000,0.959315,997.65,0,0,154.726334,High
167,168,1000.000000,0.055556,NaN,611.574748,9.090909,0.559710,196.911295,22.086661,47.899686,...,NaN,13.333333,1,13.333333,0.959315,NaN,0,0,108.760757,High
173,174,987.058823,1.944444,35.714286,611.574748,9.090909,0.564185,196.920470,22.086661,NaN,...,240.200167,20.000000,1,20.000000,0.959315,NaN,0,1,210.359725,High
180,181,976.470588,1.944444,NaN,611.683289,NaN,2.495659,201.607536,NaN,47.909346,...,NaN,11.333333,3,11.333333,2.500659,NaN,1,1,224.629948,High
184,185,930.588235,NaN,35.714286,611.574748,9.090909,NaN,NaN,22.086661,47.899686,...,30.025021,NaN,1,NaN,NaN,NaN,0,0,117.524957,High
193,194,895.294118,4.666667,214.285714,766.523287,10.909091,2.477614,210.337302,NaN,58.632548,...,NaN,3.000000,1,3.000000,2.354216,NaN,1,0,167.903615,High
200,201,852.941177,0.333333,142.857143,611.574748,22.727273,0.559710,196.911295,22.086661,47.899686,...,NaN,4.333333,1,4.333333,0.959315,NaN,1,0,159.562823,High
201,202,982.352941,0.388889,178.571429,611.574748,5.181818,0.563601,196.939267,22.086661,NaN,...,80.066722,NaN,1,NaN,0.962847,NaN,0,1,99.771084,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33775,33776,956.470588,2.391111,285.714286,616.565916,45.454545,2.114719,200.705860,NaN,48.106831,...,350.291910,12.466667,3,12.466667,2.707076,NaN,0,1,106.435456,High
33779,33780,950.588235,0.111111,NaN,613.299160,15.454545,0.696052,197.248382,0.453455,49.649143,...,NaN,8.333333,3,8.333333,1.081685,NaN,0,1,123.901893,High
33789,33790,887.058823,1.555556,35.714286,611.945890,NaN,4.189424,209.297723,NaN,47.907199,...,NaN,3.333333,2,4.129333,3.599994,NaN,1,1,159.698795,High
33798,33799,992.941177,4.166667,NaN,641.775602,8.181818,2.242920,200.401890,NaN,58.632548,...,380.316931,7.266667,2,7.266667,1.967241,1000.00,1,0,103.077453,High
33806,33807,936.470588,NaN,NaN,614.878267,7.272727,0.823204,197.326854,NaN,58.632548,...,50.041701,NaN,3,NaN,1.190769,NaN,0,0,120.996558,High
33810,33811,863.529412,0.416667,571.428571,712.276942,4.090909,1.306241,199.620494,16.983158,58.632548,...,NaN,3.334000,1,3.334000,1.691375,942.53,1,0,101.970740,High
33817,33818,874.117647,0.300000,35.714286,642.053959,15.454545,1.661557,198.892055,NaN,58.632548,...,60.050042,NaN,1,NaN,1.721673,NaN,0,0,113.046472,High
33819,33820,983.529412,2.555556,NaN,747.747322,17.727273,6.657590,211.184465,NaN,58.632548,...,100.083403,6.666667,1,6.666667,5.930580,NaN,5,0,545.191050,High
33822,33823,970.588235,0.027778,NaN,617.488520,11.363636,0.706571,197.283159,52.557954,58.632548,...,NaN,20.070000,1,11.403333,1.175227,NaN,0,0,124.533563,High
33852,33853,961.176471,0.222222,142.857143,688.056386,25.909091,4.500390,211.403519,NaN,58.372812,...,NaN,NaN,1,NaN,3.151828,NaN,0,1,369.884682,High
33856,33857,989.411765,1.944444,142.857143,612.369553,9.090909,0.644979,197.077824,198.493333,58.632548,...,400.333611,33.333333,1,33.333333,1.012429,NaN,1,1,96.041308,High
33857,33858,984.705882,0.083333,NaN,651.059420,18.181818,2.875443,201.894103,NaN,58.632548,...,80.066722,12.333333,2,12.333333,2.531679,NaN,0,0,123.636833,High
33873,33874,867.058823,0.166667,285.714286,611.574748,8.181818,0.804364,199.696800,53.832761,NaN,...,130.108424,8.866667,1,8.866667,1.108456,1000.00,1,1,50.707401,High
33875,33876,914.117647,1.230000,NaN,616.310317,22.727273,0.838732,197.435478,NaN,56.029829,...,NaN,12.466667,2,16.966667,1.120563,814.29,0,1,127.500861,High
33876,33877,836.470588,0.388889,178.571429,658.858666,8.181818,1.507774,198.893772,NaN,58.632548,...,40.033361,NaN,1,NaN,1.586573,NaN,1,0,386.213425,High
33879,33880,942.352941,0.100000,500.000000,620.933844,6.818182,1.324433,198.425953,NaN,58.632548,...,NaN,11.000000,2,13.866667,1.512478,942.91,0,0,75.306368,High
33900,33901,967.058823,1.944444,NaN,615.151372,7.272727,0.634406,197.056773,2.652282,58.632548,...,280.233528,13.333333,1,13.333333,1.030413,NaN,0,0,127.573150,High
33929,33930,948.235294,0.555556,NaN,667.930652,NaN,1.216801,198.210834,NaN,58.632548,...,NaN,16.666667,1,16.666667,1.417427,NaN,0,0,106.929432,High
33937,33938,896.470588,33.333333,NaN,611.574748,18.181818,1.438470,197.624481,22.086661,NaN,...,210.175146,NaN,2,NaN,1.818921,NaN,0,1,500.289157,High
33939,33940,996.470588,0.111111,NaN,635.984377,16.363636,1.300201,198.651055,NaN,58.632548,...,150.125104,3.533333,1,3.533333,1.848825,NaN,0,0,101.268503,High
33940,33941,978.823529,0.083333,NaN,647.326985,NaN,2.620273,200.678306,NaN,58.576737,...,18.348624,34.666667,1,34.666667,2.555539,NaN,0,0,181.578313,High
33951,33952,970.588235,1.666667,71.428571,659.483657,31.818182,4.385415,203.941649,NaN,58.632548,...,NaN,6.666667,1,6.666667,3.673913,NaN,1,0,112.292599,High
33952,33953,NaN,0.072222,35.714286,614.795985,5.909091,0.794336,197.428688,NaN,58.632548,...,10.008340,36.800000,1,36.800000,1.053355,NaN,0,0,99.533563,High
33954,33955,841.176471,0.111111,NaN,615.413973,25.909091,0.722278,197.297560,NaN,58.632548,...,200.166806,NaN,1,3.533333,1.060869,NaN,0,0,105.552496,High
33962,33963,887.058823,0.833333,892.857143,611.574748,3.909091,NaN,NaN,22.086661,47.899686,...,80.066722,NaN,0,NaN,NaN,NaN,0,0,561.605852,High
33963,33964,895.294118,0.011111,71.428571,612.766956,NaN,1.046785,197.200863,NaN,56.759663,...,NaN,NaN,6,NaN,1.298031,NaN,0,1,119.485370,High
33967,33968,925.882353,1.318889,NaN,611.678037,18.181818,0.572409,196.926122,66.123092,58.632548,...,NaN,25.333333,1,25.333333,0.969945,NaN,0,0,101.080895,High
33984,33985,NaN,0.138889,214.285714,613.663300,5.454545,0.657134,197.108292,NaN,58.632548,...,10.008340,7.000000,2,7.000000,1.032655,785.48,0,0,84.423408,High
33986,33987,889.411765,1.944444,35.714286,631.887803,16.818182,1.600791,199.210807,NaN,58.632548,...,70.058382,16.653333,1,16.653333,1.553924,NaN,1,0,153.981067,High
33999,34000,917.647059,0.138889,428.571429,650.416923,11.818182,2.640652,201.389811,NaN,58.632548,...,150.125104,5.400000,1,10.000000,2.319554,942.85,1,0,52.588640,High

In [5]:
y = train["VAR21"]
X = train.drop(["VAR21"], axis=1)
leaderboard
comb = X.append(leaderboard)
comb.iloc[:34000, :]
comb.iloc[34000:, :]
comb['VAR6_1'] = comb['VAR6'].rank()/len(comb['VAR6'])
comb['VAR3_1'] = comb['VAR3'].rank()/len(comb['VAR3'])
comb['VAR12_1'] = comb['VAR12'].rank()/len(comb['VAR12'])
comb['VAR11_1'] = comb['VAR11'].rank()/len(comb['VAR11'])

X = comb.iloc[:34000, :]
leaderboard = comb.iloc[34000:, :]

In [6]:
from sklearn.preprocessing import LabelEncoder

for c in X.columns:
    if X[c].dtype == 'object':
        lbl = LabelEncoder() 
        lbl.fit(list(X[c].values) + list(test[c].values) + list(leaderboard[c].values)) 
        X[c] = lbl.transform(list(X[c].values))
        test[c] = lbl.transform(list(test[c].values))
        leaderboard[c] = lbl.transform(list(leaderboard[c].values))

/Users/vrishank/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/Users/vrishank/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [94]:
lbl = LabelEncoder() 
lbl.fit(list(y.values)) 
y = lbl.transform(list(y))

In [7]:
X["VAR21"]=y

/Users/vrishank/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [14]:
X[X["VAR21"]=="High"].describe()

               VAR1         VAR2         VAR3         VAR4         VAR5         VAR6         VAR7         VAR8         VAR9        VAR10        VAR11        VAR12        VAR13        VAR14        VAR15        VAR16        VAR17       VAR18        VAR19        VAR20       VAR6_1       VAR3_1      VAR12_1      VAR11_1
count   3747.000000  3635.000000  3605.000000  2679.000000  3747.000000  3397.000000  3657.000000  3657.000000  1843.000000  3163.000000  3105.000000  2677.000000  3036.000000  3747.000000  3084.000000  3650.000000  1358.000000  3747.00000  3747.000000  3747.000000  3397.000000  3605.000000  2677.000000  3105.000000
mean   16952.846010   917.761955     1.744415   236.177945   634.036341    17.180884     2.772040   201.223055    58.551239    56.505182     6.079924   129.090890    13.040995     5.726448    13.821024     2.611842   799.869831     0.43795     0.345877   179.900710     0.476238     0.521747     0.366311     0.403781
std     9887.593142    49.282510     6.013518   225.428049    32.610055    32.118332    13.109671    13.701143    90.842216     3.949686    11.988400   125.874177    12.544181     5.185111    13.979242     9.129811   284.010325     0.75128     0.475717   173.414658     0.260795     0.278876     0.197305     0.225824
min        2.000000   750.588235     0.001333    18.928571   493.425349     0.318182     0.559710   103.554408     0.141170    44.259100     0.000693     0.834028     0.133333     0.000000     0.133333     0.959315     0.490000     0.00000     0.000000     0.000000     0.000841     0.000057     0.009795     0.000477
25%     8465.000000   883.529412     0.111111    71.428571   611.700796     6.818182     0.738726   197.307505    11.242252    57.249082     0.702687    30.025021     6.333333     2.000000     6.666667     1.069801   687.535000     0.00000     0.000000    99.960413     0.248386     0.290966     0.202534     0.206568
50%    17045.000000   923.529412     0.333333   142.857143   621.455544    11.363636     1.175326   198.274353    22.086661    58.632548     2.410203    90.075063    10.000000     2.000000    11.066667     1.386909   950.960000     0.00000     0.000000   115.234079     0.514739     0.556216     0.378886     0.413205
75%    25625.000000   956.470588     1.666667   321.428571   642.253536    18.181818     2.185069   200.767449    64.799090    58.632548     6.662361   201.834862    16.666667    10.000000    16.666667     2.161681  1000.000000     1.00000     1.000000   170.482788     0.689909     0.798761     0.538136     0.599398
max    34000.000000  1000.000000   173.144444  1000.000000   910.236008   772.727273   649.324982   619.843038   789.896518    71.773863   349.381719   990.825688   233.333333    20.000000   333.333333   420.464217  1000.000000     9.00000     1.000000  1000.000000     0.896307     0.901364     0.688273     0.777295

In [15]:
X[X["VAR21"]=="Medium"].describe()

               VAR1          VAR2          VAR3          VAR4          VAR5          VAR6          VAR7          VAR8         VAR9         VAR10         VAR11         VAR12         VAR13         VAR14         VAR15         VAR16        VAR17         VAR18         VAR19         VAR20        VAR6_1        VAR3_1       VAR12_1       VAR11_1
count  18172.000000  17607.000000  16405.000000  11031.000000  18171.000000  16339.000000  17841.000000  17841.000000  9523.000000  15962.000000  14336.000000  12506.000000  13806.000000  18172.000000  14067.000000  17827.000000  5994.000000  18172.000000  18172.000000  18172.000000  16339.000000  16405.000000  12506.000000  14336.000000
mean   16950.863856    923.313054      1.273387    225.169069    630.070284     15.884088      1.859503    199.669676    53.989727     56.594329      5.018778    125.313861     12.065549      5.358078     12.776795      1.925887   811.165484      0.413053      0.280101    161.392771      0.464848      0.465035      0.359122      0.382084
std     9799.856224     47.598050     16.965005    228.041421     28.684810     29.887638      6.017087      8.932626    84.489324      8.508724      9.022648    123.814528      9.800494      4.929200     10.626463      4.450033   266.841872      0.676241      0.449061    123.996532      0.254003      0.254385      0.200168      0.221631
min        3.000000    742.352941      0.001333     28.571429    347.053355      0.006364      0.559710    156.320348     0.004278     38.831492      0.000693      0.834028      0.133333      0.000000      0.133333      0.959315     0.340000      0.000000      0.000000      0.000000      0.000045      0.000057      0.009795      0.000477
25%     8439.750000    890.588235      0.083333     71.428571    611.851354      6.818182      0.686092    197.178675     9.013480     58.039825      0.625766     20.016681      6.333333      2.000000      6.666667      1.038192   704.872500      0.000000      0.000000    103.747418      0.248386      0.219511      0.187989      0.191102
50%    16876.500000    930.588235      0.166667    142.857143    619.423013     11.181818      0.969908    197.838911    22.086661     58.632548      1.999956     88.407006     10.000000      2.000000     10.666667      1.245444   955.015000      0.000000      0.000000    116.203098      0.470534      0.460250      0.371102      0.379568
75%    25435.250000    960.000000      0.555556    321.428571    635.303365     18.181818      1.671585    199.504530    59.447470     58.632548      5.632931    200.166806     16.000000     10.000000     16.666667      1.771584  1000.000000      1.000000      1.000000    157.630379      0.689909      0.674170      0.528216      0.571361
max    33997.000000   1000.000000   1000.000000   1000.000000   1000.000000    909.090818    457.248678    563.885363   832.084907   1000.000000    239.445140   1000.000000    333.333333     21.000000    333.333333    333.509445  1000.000000     12.000000      1.000000   1000.000000      0.896455      0.901750      0.688557      0.777227

In [16]:
X[X["VAR21"]=="Low"].describe()

               VAR1          VAR2          VAR3         VAR4          VAR5          VAR6          VAR7          VAR8         VAR9         VAR10        VAR11        VAR12        VAR13         VAR14        VAR15         VAR16        VAR17         VAR18         VAR19         VAR20        VAR6_1        VAR3_1      VAR12_1      VAR11_1
count  12081.000000  11797.000000  10605.000000  7796.000000  12081.000000  10769.000000  11667.000000  11667.000000  6817.000000  10325.000000  8994.000000  8315.000000  8636.000000  12081.000000  8825.000000  11657.000000  4454.000000  12081.000000  12081.000000  12081.000000  10769.000000  10605.000000  8315.000000  8994.000000
mean   17089.941892    908.439733      0.669297   284.577485    633.064683     13.792250      2.130035    200.142140    52.753379     56.344940     5.858337   101.404708    10.583967      5.616091    11.459557      2.183283   841.422414      0.368678      0.310239    155.548788      0.413889      0.404689     0.317351     0.394161
std     9815.626310     52.935449      2.971870   259.405371     33.255638     26.799619     10.900342     13.429409    82.887877      4.187322    14.293639   112.130088    12.256101      5.120481    13.409836     11.303689   247.695903      0.674875      0.462611    100.732417      0.259878      0.252477     0.194389     0.228871
min        1.000000    730.588235      0.001400    28.571429    523.291825      0.005000      0.353228      0.000000     0.051334     13.028620     0.000693     0.834028     0.082667      0.000000     0.133333      0.959315     0.130000      0.000000      0.000000      3.442341      0.000023      0.000114     0.009795     0.000477
25%     8587.000000    870.588235      0.077778    71.428571    611.574748      5.909091      0.686888    197.198111     7.901232     56.300297     0.641704    15.012510     5.000000      2.000000     5.666667      1.034674   774.395000      0.000000      0.000000    106.199656      0.181886      0.185920     0.151443     0.194580
50%    17140.000000    914.117647      0.138889   178.571429    619.879939      9.090909      0.999414    197.928150    22.086661     58.632548     2.182557    60.050042     8.466667      2.000000     9.666667      1.260969   977.015000      0.000000      0.000000    119.690189      0.400023      0.374875     0.298023     0.395727
75%    25548.000000    950.588235      0.388889   428.571429    639.107577     14.545455      1.716341    199.702819    57.237948     58.632548     6.529481   159.716430    13.333333     10.000000    14.666667      1.829128  1000.000000      1.000000      1.000000    159.879518      0.631966      0.598261     0.479534     0.596182
max    33999.000000   1000.000000    150.000000  1000.000000    929.293831    909.090818    681.582083   1000.000000   993.061289    135.213659   824.334457  1000.000000   775.000000     21.000000   775.000000   1000.000000  1000.000000     14.000000      1.000000   1000.000000      0.896455      0.901341     0.688557     0.777341

In [97]:
import xgboost as xgb

# prepare dict of params for xgboost to run with
xgb_params = {
    'n_trees': 100, 
    'eta': 0.01,
    'max_depth': 6,
    'subsample': 0.93,
    'objective': 'multi:softmax',
    'eval_metric': 'mlogloss',
    'silent': 1,
    'num_class' :3
}

# form DMatrices for Xgboost training
dtrain = xgb.DMatrix(X, y)
dtest = xgb.DMatrix(leaderboard)

# xgboost, cross-validation
cv_result = xgb.cv(xgb_params, 
                   dtrain, 
                   num_boost_round=1200, # increase to have better results (~700)
                   verbose_eval=50,
                   early_stopping_rounds=50
                  )

num_boost_rounds = len(cv_result)
print('num_boost_rounds=' + str(num_boost_rounds))

# train model
model = xgb.train(dict(xgb_params, silent=1), dtrain, num_boost_round=num_boost_rounds)


# check f2-score (to get higher score - increase num_boost_round in previous cell)

# make predictions and save results
y_preds = model.predict(dtest)
y_preds

[0]	train-mlogloss:1.09548+4.92702e-05	test-mlogloss:1.09573+1.81904e-05
[50]	train-mlogloss:0.981571+0.00137387	test-mlogloss:0.99371+0.0011203
[100]	train-mlogloss:0.917239+0.0017804	test-mlogloss:0.939877+0.00227647
[150]	train-mlogloss:0.877498+0.0019657	test-mlogloss:0.909705+0.00336758
[200]	train-mlogloss:0.850712+0.00209109	test-mlogloss:0.892069+0.00421924
[250]	train-mlogloss:0.831292+0.00223869	test-mlogloss:0.881333+0.00482168
[300]	train-mlogloss:0.816452+0.00218476	test-mlogloss:0.874592+0.00524562
[350]	train-mlogloss:0.804671+0.00200682	test-mlogloss:0.870406+0.00546259
[400]	train-mlogloss:0.79472+0.00195092	test-mlogloss:0.867683+0.00569533
[450]	train-mlogloss:0.786182+0.00197726	test-mlogloss:0.865938+0.00592527
[500]	train-mlogloss:0.77829+0.00222674	test-mlogloss:0.864774+0.00591357
[550]	train-mlogloss:0.77096+0.00222162	test-mlogloss:0.864018+0.0059661
[600]	train-mlogloss:0.764159+0.00252672	test-mlogloss:0.863466+0.00596393
[650]	train-mlogloss:0.757716+0.0025084	test-mlogloss:0.863095+0.00603162
[700]	train-mlogloss:0.751645+0.0025215	test-mlogloss:0.862849+0.00601813
[750]	train-mlogloss:0.74591+0.00257571	test-mlogloss:0.862699+0.00611033
[800]	train-mlogloss:0.740288+0.00257436	test-mlogloss:0.862612+0.00614646
[850]	train-mlogloss:0.734825+0.00290972	test-mlogloss:0.862646+0.0062075
num_boost_rounds=824

array([2., 1., 1., ..., 2., 2., 1.], dtype=float32)

In [99]:
d = {'col1': leaderboard["VAR1"], 'col2': [int(i) for i in y_preds]}
df = pd.DataFrame(data=d)
df["col2"][df["col2"] == 0] = "High"
df["col2"][df["col2"] == 1] = "Low"
df["col2"][df["col2"] == 2] = "Medium"

import shutil 

filename = "Quant404_IITGuwahati_34"
df.to_csv(filename+'.csv', index=False, header=False)
shutil.copyfile("Quant404_IITGuwahati_27.ipynb", filename+".ipynb")

'Quant404_IITGuwahati_34.ipynb'

In [100]:
import xgboost as xgb

# prepare dict of params for xgboost to run with
xgb_params = {
    'n_trees': 700, 
    'eta': 0.01,
    'max_depth': 5,
    'subsample': 0.93,
    'objective': 'multi:softmax',
    'eval_metric': 'mlogloss',
    'silent': 1,
    'num_class' :3
}

# form DMatrices for Xgboost training
dtrain = xgb.DMatrix(X, y)
dtest = xgb.DMatrix(leaderboard)

# xgboost, cross-validation
cv_result = xgb.cv(xgb_params, 
                   dtrain, 
                   num_boost_round=1200, # increase to have better results (~700)
                   verbose_eval=50,
                   early_stopping_rounds=50
                  )

num_boost_rounds = len(cv_result)
print('num_boost_rounds=' + str(num_boost_rounds))

# train model
model = xgb.train(dict(xgb_params, silent=1), dtrain, num_boost_round=num_boost_rounds)


# check f2-score (to get higher score - increase num_boost_round in previous cell)

# make predictions and save results
y_preds = model.predict(dtest)
y_preds

[0]	train-mlogloss:1.09567+4.8833e-05	test-mlogloss:1.09581+2.01163e-05
[50]	train-mlogloss:0.989498+0.00136209	test-mlogloss:0.996145+0.00117626
[100]	train-mlogloss:0.930591+0.00182183	test-mlogloss:0.943139+0.00236491
[150]	train-mlogloss:0.895265+0.00211722	test-mlogloss:0.913196+0.00329876
[200]	train-mlogloss:0.872194+0.00231327	test-mlogloss:0.895454+0.00412207
[250]	train-mlogloss:0.856103+0.0025193	test-mlogloss:0.884557+0.00468988
[300]	train-mlogloss:0.844072+0.00254194	test-mlogloss:0.877572+0.00508902
[350]	train-mlogloss:0.834776+0.00244383	test-mlogloss:0.87317+0.00546055
[400]	train-mlogloss:0.827106+0.00240398	test-mlogloss:0.870241+0.00571325
[450]	train-mlogloss:0.820567+0.00222556	test-mlogloss:0.868161+0.00594289
[500]	train-mlogloss:0.814756+0.00231773	test-mlogloss:0.866684+0.00597291
[550]	train-mlogloss:0.80936+0.0022704	test-mlogloss:0.86569+0.00608653
[600]	train-mlogloss:0.804402+0.00229073	test-mlogloss:0.864922+0.00606212
[650]	train-mlogloss:0.799853+0.00220623	test-mlogloss:0.864357+0.00615925
[700]	train-mlogloss:0.795518+0.00220229	test-mlogloss:0.863913+0.00613957
[750]	train-mlogloss:0.791493+0.00221418	test-mlogloss:0.863644+0.00619441
[800]	train-mlogloss:0.787521+0.00224578	test-mlogloss:0.863446+0.00621573
[850]	train-mlogloss:0.783666+0.0024042	test-mlogloss:0.863338+0.006211
[900]	train-mlogloss:0.779858+0.00242892	test-mlogloss:0.863266+0.00618008
[950]	train-mlogloss:0.776132+0.00239406	test-mlogloss:0.863193+0.00616428
[1000]	train-mlogloss:0.77254+0.00245859	test-mlogloss:0.863142+0.00614909
num_boost_rounds=997

array([2., 1., 1., ..., 2., 2., 1.], dtype=float32)

In [17]:
sub=[]
for i in y_preds:
    if i[0]>i[1] and i[0]>i[2]:
        sub.append("High")
    elif i[1]>i[0] and i[1]>i[2]:
        sub.append("Low")
    else:
        sub.append("Medium")
print(list(y).count(0)/len(y))
print(list(y).count(1)/len(y))
print(list(y).count(2)/len(y))
print(sub.count("High")/len(sub))
print(sub.count("Low")/len(sub))
print(sub.count("Medium")/len(sub))
print(len(sub))

NameError: name 'y_preds' is not defined

In [78]:
d = {'col1': leaderboard["VAR1"], 'col2': sub}
df = pd.DataFrame(data=d)
import shutil 

filename = "Quant404_IITGuwahati_33"
df.to_csv(filename+'.csv', index=False, header=False)
shutil.copyfile("Quant404_IITGuwahati_22.ipynb", filename+".ipynb")

'Quant404_IITGuwahati_33.ipynb'

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.metrics.scorer import make_scorer
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    train_size=30000, test_size=4000)


def my_custom_accuracy(y_true, y_pred):
    total=0
    for t,p in zip(y_true, y_pred):
        if(t==p):
            total+=1000
        if(t==0 and p==1):
            total-=100
        if(t==0 and p==2):
            total-=50
        if(t==2 and p==1):
            total-=50
        if(t==2 and p==0):
            total-=100
        if(t==1 and p==2):
            total-=100
        if(t==1 and p==0):
            total-=200
    return total

# Make a custom a scorer from the custom metric function
# Note: greater_is_better=False in make_scorer below would mean that the scoring function should be minimized.
my_custom_scorer = make_scorer(my_custom_accuracy, greater_is_better=True)
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    train_size=30000, test_size=4000)

#tpot = TPOTClassifier(generations=10, population_size=20, verbosity=3, scoring=my_custom_scorer, cv=3)

In [ ]:
tpot.fit(X_train, y_train)

30 operators have been imported by TPOT.

A Jupyter Widget

Skipped pipeline #14 due to time out. Continuing to the next pipeline.
Skipped pipeline #17 due to time out. Continuing to the next pipeline.